services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    environment:
      MYSQL_DATABASE: productservice
      MYSQL_ROOT_PASSWORD: Anirban@2020
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: