
services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    environment:
      MYSQL_DATABASE: inventoryservice
      MYSQL_ROOT_PASSWORD: Anirban@2020
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql-data:
